describe('Chapter page for authenticated user that owns the chapter', function() {
  const username = 'testi'
  const password = 'testi'
  beforeEach(function() {
    cy.visit('/login')
    cy.get('#usernameField')
      .type(username)
    cy.get('#passwordField')
      .type(password)
    cy.get('form')
      .submit()
    cy.wait(1000)
    cy.visit('/chapters')
    cy.contains('Mon Test')
      .click()
  })

  it('new word can be added to vocabulary and removed', function() {
    cy.get('[data-cy=add-word-button]')
      .click()
    cy.get('.autosuggest > input')
      .type('aujourd\'hui')
      .type('{downarrow}')
    cy.get('form')
      .submit()
    cy.get('[data-cy=search-field]')
      .type('aujourd\'hui')
    cy.get('table')
      .contains('aujourd\'hui')
    cy.get('[type="checkbox"]')
      .first()
      .check()
    cy.get('[data-cy=remove-words-button]')
      .click()
    cy.get('table')
      .contains('aujourd\'hui')
      .should('not.exist')
  })

  it('remove and save buttons are visible in the word detail modal', function() {
    cy.get('[data-cy=word-lemma]')
      .first()
      .click()
    cy.get('[data-cy=word-details-modal]')
      .should('be.visible')
    cy.get('[data-cy=save-word-button]')
      .should('be.visible')
    cy.get('[data-cy=remove-word-button]')
      .should('be.visible')
  })

  it('buttons for editing chapter and vocabulary are visible', function() {
    cy.get('[data-cy=publish-chapter-button]')
      .should('be.visible')
    cy.get('[data-cy=edit-chapter-button]')
      .should('be.visible')
    cy.get('[data-cy=remove-chapter-button]')
      .should('be.visible')
    cy.get('[data-cy=add-word-button]')
      .should('be.visible')
    cy.get('[data-cy=remove-words-button]')
      .should('be.visible')
  })
})
