describe('Chapters page for authenticated user', function() {
  const username = 'testi'
  const password = 'testi'

  it('user can create a new chapter', function () {
    cy.visit('/login')
    cy.get('#usernameField')
      .type(username)
    cy.get('#passwordField')
      .type(password)
    cy.get('form')
      .submit()
    cy.wait(1000)
    cy.get('[data-cy=new-chapter-button]')
      .click()
    cy.url()
      .should('include', '/new')
    cy.get('[data-cy=chapter-title-field]')
      .type('Le Test')
    cy.get('[data-cy=chapter-body-field]')
      .type('C\'est mon chapitre de test')
    cy.get('form')
      .submit()
    cy.get('[data-cy=analyzing-spinner]')
    cy.wait(30000)
    cy.url()
      .should('include', '/chapters')
    cy.get('h1')
      .contains('Le Test')
    cy.get('[data-cy=return-to-chapters-button]')
      .click()
    cy.get('[type="checkbox"]')
      .first()
      .check()
    cy.get('[data-cy=remove-chapters-button]')
      .click()
    cy.wait(1000)
    cy.contains('Le Test').should('not.exist')
  })
})